############################################################
# 02 - LOAD DATA
############################################################


# ==========================================================
# SEQUENCE DATA

## Load pipeline outputs
data.tax <- tax_table(as.matrix(read.table("taxonomy.vsearch", header = TRUE, row.names = 1, fill = TRUE, sep = ",")))
data.otu <- otu_table(read.table("asv_table.merge.txt", header = TRUE, row.names = 1, check.names = FALSE), taxa_are_rows = TRUE)

## Load phylogeny if generated by the pipeline
if (pipeline_phylogeny == 1) {
  data.tre <- read.tree("asvs.tre")
}

# ==========================================================
# SAMPLE METADATA

## Load QC metadata
# Technical/QC metadata generated automatically by the pipeline.
qc.map <- read_sample_metadata_table("samples_metadata.csv", sep = ",")


## Load biological metadata (optional)
# Add project-specific metadata and specify the column containing sample IDs.
# bio.map <- read_sample_metadata_table(
#   "YOUR_SAMPLE_DATA_FILE.csv",
#   sample_id_col = "Sample_ID",
#   sep = ","
# )


# ----------------------------------------------------------
# Harmonise sample IDs if necessary

# Sample IDs must match between the ASV table and metadata.
# Apply transformations only where required.

## Remove sequencing-specific suffix
# sample_names(qc.map) <- gsub(".ITS_S1", "", sample_names(qc.map), fixed = TRUE)

## Replace characters
# sample_names(qc.map) <- gsub("-", ".", sample_names(qc.map), fixed = TRUE)
# sample_names(bio.map) <- gsub("-", ".", sample_names(bio.map), fixed = TRUE)


# ----------------------------------------------------------
# Merge metadata

## With biological metadata
# metadata.result <- merge_sample_metadata(
#   qc_metadata = qc.map,
#   biological_metadata = bio.map,
#   generate_pseudo = FALSE
# )

## Without biological metadata
metadata.result <- merge_sample_metadata(
  qc_metadata = qc.map,
  biological_metadata = NULL,
  generate_pseudo = TRUE
)

data.map <- metadata.result$metadata

## Troubleshooting
# metadata.result$overlap
# metadata.result$only_in_QC
# metadata.result$only_in_biological


# ==========================================================
# BUILD PHYLOSEQ OBJECT

## Construct phyloseq object
if (pipeline_phylogeny == 1) {
  data.ps <- merge_phyloseq(data.otu, data.tax, data.map, data.tre)
} else {
  data.ps <- merge_phyloseq(data.otu, data.tax, data.map)
}

